### ISSUE TITLE
Strange. GQRX tuning reverses direction.

### ISSUE THREAD

**Issue by JohnCC330** [gqrx-sdr/gqrx#1002]
Using Slackware64-current Linux, and rtlsdr dongle, GQRX 2.14.6.

A couple of days ago, suddenly GQRX reverse tuning direction: In a segment of frequences where I had bookmarked several frequences, suddenly the actual peaks in the spectrum were in the opposite direction. 

Another way to describe the issue is that a peak in the spectrum, when tuning in 10 or 100kHz steps, moved in the opposite direction from the frequency scale, instead of following it, by double the step. Eg. a 100kHz step in one direction produced a 200kHz opposite.

My first reaction was that some kind of mixing had occured and I was tuning an image frequency. But i was happening with _all_ the known signals. I had little time to investigate it further.

Then, after a day of inactivity, things went back to normal. 'Bookmarks' coicided with actual signal again, and tuning was back to normal.

Q: Could this have been some control setting? I couldn't find anything related.

**Comment by shuyuan-liu** [comment]
The "Swap IQ" option might have been activated in the Input controls tab for some reason. Could you try turning this option on and see if it produces the same effect?

**Comment by JohnCC330** [comment]
Why would IQ influence the frequency? Am I misunderstanding the meaning of IQ?

**Comment by shuyuan-liu** [comment]
To be honest I don't know the details of how swapping I and Q reflects the spectrum display but... it does. I/Q refers to the complex (in-phase and quadrature) samples used by SDRs and in signal processing.

**Comment by argilo** [comment]
The "Swap I/Q" setting does indeed have the effect of inverting frequencies above and below the LO frequency. But I doubt that's what happened here, because it wouldn't explain the tuning step being doubled. That strongly suggests to me that you were seeing mixing products, perhaps generated by a strong local interfering signal.

I doubt that this behaviour is due to a bug in Gqrx, so I'll close off this issue for now.

**Comment by JohnCC330** [comment]
On Mon, 29 Nov 2021 16:20:54 -0800
Clayton Smith ***@***.***> wrote:

> I doubt that this behaviour is due to a bug in Gqrx, so I'll close
> off this issue for now.

Yes, Clayton - probably my bad luck I found several stations that exhibited that
strange behaviour.

The reversed tuning on switching I/Q does confuse me... Is there an explanation
for this?

John

**Comment by argilo** [comment]
> The reversed tuning on switching I/Q does confuse me... Is there an explanation for this?

Swapping the I & Q channels of a quadrature signal is equivalent to conjugating the complex samples and multiplying them by j. Complex conjugation inverts the signal in the frequency domain, and multiplication by j only affects the phase.

**Comment by JohnCC330** [comment]
On Mon, 29 Nov 2021 16:53:56 -0800
Clayton Smith ***@***.***> wrote:

> Swapping the I & Q channels of a quadrature signal is equivalent to
> conjugating the complex samples and multiplying them by j. Complex
> conjugation inverts the signal in the frequency domain, and
> multiplication by j only affects the phase.

Thanks! There's a nice answer here:

https://dsp.stackexchange.com/questions/23733/conjugation-in-fourier-transform/23734
