### ISSUE TITLE
BUG: Changing IO devices stops the DSP

### ISSUE THREAD

**Issue by vladisslav2011** [gqrx-sdr/gqrx#1019]
Regression.

Steps to reproduce:
1. Start gqrx, select some hardware device, start the DSP
2. Go back to I/O device dialog without stopping the DSP and choose some other device

Expected behavior:
The DSP restarts after switching devices. Waterfall continues to update with data from selected device, the sound should continue to output too.

Observer behavior:
The DSP does not restart.

Some old gqrx version did not suffer from this bug, so this is a regression...

**Comment by argilo** [comment]
I was curious where this bug came from. Looks like it was introduced in #663:

https://github.com/gqrx-sdr/gqrx/commit/a91f62396b0f8931e41ba86814adf3f6df5a32b2#diff-2fc3518522047c9d0c5d1f75d1de006499a71e9812311c7228c892a5250bad48R1796
