### ISSUE TITLE
I/Q tool file selector randomly jumps to current selection

### ISSUE THREAD

**Issue by argilo** [gqrx-sdr/gqrx#1037]
Steps to reproduce:

1. Create enough I/Q recording files such that they take up more than one page in the I/Q tool.
2. Open the I/Q tool and click on the first recording file.
3. Scroll down to the bottom of the list of I/Q files.

Within one second, you'll be returned to the top of the list. This makes it very difficult to select the I/Q files you want.

This happens because `CIqTool::timeoutFunction` executes once per second and calls `CIqTool::refreshDir`, which clears and rebuilds the list, then calls `QListWidget::setCurrentRow`. I imagine there's a better way to keep the file list up to date.

**Comment by vladisslav2011** [comment]
I've noticed this issue too.
It may fixed by merging https://github.com/gqrx-sdr/gqrx/pull/1011
