### ISSUE TITLE
My device disappeared when I open Gqrx

### ISSUE THREAD

**Issue by langonginc** [gqrx-sdr/gqrx#1103]
I bought an SDR device (RTL-SDR), and I connected and listened successfully yesterday. But today, when I open GQRX, It seemed the application cannot find my device (I connected with USB, and the light is on normally). How can I fix it?

Gqrx logs:

```bash
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.9.4.0
built-in source types: file rtl rtl_tcp uhd hackrf bladerf rfspace airspy soapy redpitaya 
gr::log :WARN: file_source0 - file size is not a multiple of item size
Resampling audio 96000 -> 48000
BandPlanFile is /home/wjy/.config/gqrx/bandplan.csv
BookmarksFile is /home/wjy/.config/gqrx/bookmarks.csv
[INFO] [UHD] linux; GNU C++ version 11.1.0; Boost_107800; UHD_4.1.0.5-0-unknown
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.9.4.0
built-in source types: file rtl rtl_tcp uhd hackrf bladerf rfspace airspy soapy redpitaya 
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.9.4.0
built-in source types: file rtl rtl_tcp uhd hackrf bladerf rfspace airspy soapy redpitaya 
gr::log :WARN: file_source0 - file size is not a multiple of item size
```

P.S. After that, I restarted system and used `rtl_test` found my device.

`rtl_test` logs:

```bash
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R828D tuner
Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6 
Sampling at 2048000 S/s.

Info: This tool will continuously read from the device, and report if
samples get lost. If you observe no further output, everything is fine.

Reading samples in async mode...
Allocating 15 zero-copy buffers
lost at least   4 bytes in buffer 0
```

`Archlinux x64 5.15.21-1-lts` with `gqrx 2.15.8-1` and `gnuradio 3.9.4.0-2` installed by `pacman`.

Thank you!

**Comment by argilo** [comment]
I don't really have enough information to diagnose the problem here. The only thing that comes to mind is that perhaps another application was using the device.

Does unplugging the device and plugging it back in help?

**Comment by langonginc** [comment]
> Does unplugging the device and plugging it back in help?

I tried, but it didn't work.

**Comment by langonginc** [comment]
Thanks for help, I'm now fixed it. My device was broken. The seller exchanged of it and now can work.
