### ISSUE TITLE
gqrx-sdr installation syntax warning and warning messages

### ISSUE THREAD

**Issue by ChillVibesMushroom** [gqrx-sdr/gqrx#1125]
is this something I should worry about

running python rtupdate hooks for python3.10...
/usr/share/legion/ui/models/cvemodels.py:55: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not len(self.__cves) is 0:
/usr/share/legion/ui/models/hostmodels.py:43: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not len(self.__hosts) is 0:
/usr/share/legion/ui/models/processmodels.py:43: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not len(self.__processes) is 0:
/usr/share/legion/ui/models/scriptmodels.py:44: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not len(self.__scripts) is 0:
/usr/share/legion/ui/models/servicemodels.py:40: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not len(self.__services) is 0:
/usr/share/legion/ui/models/servicemodels.py:184: SyntaxWarning: "is not" with a literal. Did you mean "!="?

xtrx.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-kali3-amd64/kernel/drivers/media/radio/

**Comment by argilo** [comment]
As far as I can tell, those warnings are coming from packages other than Gqrx. So I'll close off this issue.
