### ISSUE TITLE
Problems with signal reception (BladeRF-x40 , GNUradio)

### ISSUE THREAD

**Issue by raul8883** [gqrx-sdr/gqrx#1131]
Hi everyone, I am having problems when I receive signals using two SDRs (BladeRF - x40), one to transmit and one to receive (I know I can transmit and receive using 1 SDR, but I need the complete schematic transmitter, receiver), the problem is the following, I have a complex signal , with the following values:
in-phase component (i(t)) tx = Ac * x(t)
quadrature component (q(t)) tx = 0
Vy (t) tx = i(t) + j q(t)
TX
![image](https://user-images.githubusercontent.com/108473482/176950471-7d387b2e-0ec9-4b73-968d-929db8cb43ca.png)

I send this signal to the channel and therefore it is received by the SDR receiver.
What I receive in the reception is not similar to what I transmitted, because of a tone appears both in its component in phase and in quadrature, by making q(t) rx /≈ q(t) tx /≈ 0.
RX
![image](https://user-images.githubusercontent.com/108473482/176950532-6e995cdb-27c9-4ad9-a37a-23370b05acd5.png)

For a better compression, I will transmit the following signal x(t) = 0 (equivalent to i(t) tx = 0, q(t) tx = 0), so in theory in reception it would only have noise, but this is not the case.
TX
![image](https://user-images.githubusercontent.com/108473482/176950592-fb2d228a-721d-469b-af9c-468f021b1f62.png)

RX
![image](https://user-images.githubusercontent.com/108473482/176950635-5230bfa7-2a42-412c-8e01-4d3a9868aa7b.png)

When I use a single SDR to transmit and receive this does not happen, I don't know if this is due to some kind of synchronization, but with this problem I can not correctly classify the type of modulation.

BLOCK SDR Transmitter.
![image](https://user-images.githubusercontent.com/108473482/176950682-6b679a34-12b0-495a-b6ee-2685f0c90df2.png)

BLOCK SDR Receiver.
![image](https://user-images.githubusercontent.com/108473482/176950724-d6ec7b6b-ccb9-4cd4-9403-d08613453ac6.png)

This is what i am getting (Frecuency Domain) when i am transmitting a message with amplitude = 0 and both SDRs have gain equal to 0

![image](https://user-images.githubusercontent.com/108473482/176950956-a88f8898-678a-4419-80c0-fadd13541a95.png)

When I increase the gain, that peak increases, in addition another peak appears symmetrical to that one with less amplitude
![image](https://user-images.githubusercontent.com/108473482/176951028-e6c6f51d-ca35-4409-820c-9263c6449068.png)

This does not happen when I transmit and receive with the same sdr,
Could this be due to mismatches between both SDRs?

I need help to know how to make it not transmit and receive that unwanted signal.
Thank you very much in advance!

**Comment by vladisslav2011** [comment]
Hello.
I think, there is better place to ask general GNU Radio questions: GNU Radio matrix chat https://matrix.to/#/#gnuradio:gnuradio.org

**Comment by argilo** [comment]
This does not appear to have any connection to Gqrx, so I'll close off the issue.
