### ISSUE TITLE
Feature request: bandplan overlay

### ISSUE THREAD

**Issue by hackery** [gqrx-sdr/gqrx#1150]
I constantly have to refer to source in other windows to identify what modes I should be expecting at each point along a band - would be very nice to have this embedded in the panadapter behind the frequency ticks:

![gqrx-bandplan](https://user-images.githubusercontent.com/308470/194674312-5fba9b0b-6e9d-46d7-a60c-908049b4d891.png)

Band plan data should be selectable from alternative files, and the colour mapping to modes selectable by the user.

**Comment by argilo** [comment]
Gqrx already has a bandplan feature; it was added in https://github.com/gqrx-sdr/gqrx/pull/767. Have you tried that? Or are you proposing changes to it?

**Comment by hackery** [comment]
!! I'd not seen that. Old release in my distro. I scanned the changelog but missed this. ty
