### ISSUE TITLE
The MacOS CI script fails to install dependencies

### ISSUE THREAD

**Issue by vladisslav2011** [gqrx-sdr/gqrx#1184]
Steps to reproduce:

1. Fork repository
2. Enable the CI
3. Create a branch
4. Push a commit with a no-breaking change (fix code formatting somewhere for example) to a newly created branch to trigger the CI

Expected behavior:

CI passes with all green checkmarks

Observed behavior:

MacOS CI failes with the following error
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-3.11
Target /usr/local/bin/2to3-3.11
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3-3.11'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.11

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.11
```

**Comment by argilo** [comment]
As mentioned in #1185, it appears that Homebrew has fixed the issue.
