### ISSUE TITLE
provide a means to change receiver frequency by mousewheel and (or) hotkeys without moving (and thus tearing) waterfall.

### ISSUE THREAD

**Issue by sibrat** [gqrx-sdr/gqrx#1192]
There is no way to change receiver frequency (not hardware frequency) rather than pinpointing it with left mouse key. It would be much more convinient do that with combination like shift + mouse wheel and page-up/page down key or maybe even make it default action and change hardware frequency with shift+scroll. Implementing issue #71 in this context also would be very nice as we are already have channel step in bandplan.

**Comment by argilo** [comment]
The receiver frequency can be adjusted with the mouse wheel. Make sure the mouse pointer is hovering over the panadapter, waterfall, or digits in the "Receiver Options" tab.

**Comment by sibrat** [comment]
> The receiver frequency can be adjusted with the mouse wheel. Make sure the mouse pointer is hovering over the panadapter, waterfall, or digits in the "Receiver Options" tab.

this indeed changes receiver IC frequency (in my case MSI001 tuning frequency), but i'm talking about receiving (demodulation) frequency

**Comment by argilo** [comment]
I'm not sure why that would be. For me it changes the demodulation frequency. I tested with an RTL-SDR.

**Comment by sibrat** [comment]
oh, i see. mouse wheel over tuning frequency changes hardware frequency, over waterfall changes demodulation frequency. Can't believe i never try this. my fault :)

**Comment by argilo** [comment]
That explains it. I'm glad to hear it's working for you now.

**Comment by sibrat** [comment]
Yes, it's very easy to overlook what exactly changes when baseband bandwidth is much wider than couple of megaherz, so maybe it worth it to somehow make presence of this difference more obvious. just suggestion...
