### ISSUE TITLE
make error !

### ISSUE THREAD

**Issue by hm123tyt** [gqrx-sdr/gqrx#1215]
when i have ‘make’,
make[2]: *** [src/CMakeFiles/gqrx.dir/build.make:1201：src/gqrx] error 1
make[1]: *** [CMakeFiles/Makefile2:233：src/CMakeFiles/gqrx.dir/all] error 2

**Comment by argilo** [comment]
Unfortunately, this is not enough information to diagnose the problem. Please provide the list of commands you executed when building, as well as the full output of each command.

**Comment by hm123tyt** [comment]
![84ef6da7b33b8761bfacb9f23a979e1](https://user-images.githubusercontent.com/81818064/228895095-9fba37f8-dfa7-4beb-b081-74510f01f8b7.png)

**Comment by argilo** [comment]
It appears that you have two conflicting versions of GNU Radio installed (3.9.8 & 3.10.1). You should uninstall one of those before attempting to build Gqrx and its dependencies.

Or instead of building from source, you could install Gqrx from the package manager with `sudo apt install gqrx-sdr`.

**Comment by argilo** [comment]
I'll close this issue off for now, since it doesn't appear to be a problem with Gqrx.
