### ISSUE TITLE
make error again！

### ISSUE THREAD

**Issue by hm123tyt** [gqrx-sdr/gqrx#1216]
"I reinstalled ubuntu and followed the steps on github to install gqrx, but the following error occurred while making. Can you tell me how to solve the problem?"
![image](https://user-images.githubusercontent.com/81818064/229000651-a420d9be-f96b-4977-9365-cbe15936d2da.png)

**Comment by argilo** [comment]
Did you build GNU Radio from source? If so, it appears that the WAV File Source & Sink blocks are not present. Those blocks are only built if the `libsndfile-dev` package is installed. You should install that package, then rebuild GNU Radio.

This does not appear to be a problem with Gqrx, so I'll close off this issue.

In the future, I would suggest asking questions like this in the support forum: https://groups.google.com/g/gqrx

**Comment by hm123tyt** [comment]
That's OK. Thank you very much!
