### ISSUE TITLE
Freq zoom slider behaves erratically

### ISSUE THREAD

**Issue by argilo** [gqrx-sdr/gqrx#1235]
Sometimes the "Freq zoom" slider refuses to decrease below a certain value, or becomes completely stuck.

Scenario 1:

1. Click "Reset" in the "FFT Settings" panel.
2. Hover over the frequency axis close to the upper frequency and zoom in to ~30x using the mouse wheel.
3. Try to drag the "Freq zoom" slider back down to 1x. It will stop well before, refusing to go any lower.

Scenario 2:

1. Click "Reset" in the "FFT Settings" panel.
2. Hover over the frequency axis close to the upper frequency and zoom in to ~30x using the mouse wheel.
3. Drag the frequency axis far enough to move beyond the end of the FFT, so that part of the display is empty.
4. Try to drag the "Freq zoom" slider back down to 1x. It will jump up to a larger value and become completely stuck.

It remains possible to zoom out by other means, just not using the "Freq zoom" slider.

**Comment by willcode** [comment]
How should the slider work when it represents zooms of 1-10000+? Is it the right GUI element now?

**Comment by argilo** [comment]
I expect it would work much better if the scale was logarithmic instead of linear.

**Comment by argilo** [comment]
I suspect scenario one has to do with zoom being centred around the demod frequency (indicated by the vertical red line in the plot). When the red line is invisible because it's outside the displayed frequency range, zooming out stops working properly.

**Comment by vladisslav2011** [comment]
I think, zoom slider and wheel zoom may behave erratically due to different zoom in/ zoom out scale factors.
https://github.com/vladisslav2011/gqrx/commit/b3eeb3258b11edb027b6719b02a699d35fb97674
(Old plotter, but wheel handling code is the same)
