### ISSUE TITLE
Detaching kernel driver on startup fails

### ISSUE THREAD

**Issue by 3v1n0** [gqrx-sdr/gqrx#1253]
I've been trying to use gqrx AppImage (and deb in Ubuntu 22.04) with a `Realtek RTL2838UHIDIR` and it gqrx was always failing to actually detach kernel driver:

```
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Detached kernel driver
No supported tuner found
```

So running it lead to no signal or results... Once I `modprobe -r`'d the relevant modules that got auto-loaded gqrx worked.

While this could be a distro issue, I've to mention that this is not a problem that I've faced when using `rtl_433` that was able to detach the kernel and results were fetched.

**Comment by argilo** [comment]
Closing, since there's nothing Gqrx can do about this.
