### ISSUE TITLE
Frequency axis in saved waterfall is incorrect

### ISSUE THREAD

**Issue by argilo** [gqrx-sdr/gqrx#1286]
In version 2.5 (released January 2016), the "Save waterfall" feature was added, which writes the current waterfall to a PNG file: efc609f0b56582cf4ac83cd98559ddbf8cd81c62

Then in version 2.6 (released October 2016), 1-2-5 scaling was added to the frequency axis of the FFT: 4268098879c3f13a3f5646ad6f96cce22475965e. Unfortunately, the "Save waterfall" functionality was overlooked, and the X coordinate calculation in `CPlotter::saveWaterfall` was not updated to include the new `adjoffset` parameter. As a result, the frequency axis is offset from its correct location.

It wouldn't be too hard to fix the X coordinate calculation, but it's probably worth considering whether the "Save waterfall" feature should remain in Gqrx. It has been broken for all but the first nine months of its existence, and the justification for its creation isn't compelling now that modern operating systems can screenshot individual windows:

> Unlike screenshots, this also works with off screen waterfalls, so one can increase the window height beyond the screen height to work around the lack of scrollable waterfall.

It seems to be a little-used feature, which makes it prone to bugs. (See #1256 for another example.)

That said, there do appear to be users of the feature, who even wish it could do more:

* #712 
* #778

My preference would be to leave screenshot functionality to the OS and remove it from Gqrx, but I'd like to hear feedback from others before making a final decision.

**Comment by willcode** [comment]
Agree. The OS screenshot will cover most uses.
