### ISSUE TITLE
Waterfall: add Clear button for waterfall

### ISSUE THREAD

**Issue by K4KDR** [gqrx-sdr/gqrx#1297]
Thanks for the new release!

In the past, if the '**WF Span**' time was changed, the waterfall would be **cleared**.

As of v2.17, I see that the waterfall no longer clears, so you have a partial display of two different rates until the 'old' value scrolls off the bottom of the screen.

Is there any method remaining that results in a clean waterfall?   I've toggled several of the settings but not found one.

Thanks!

-Scott,  K4KDR

**Comment by willcode** [comment]
It does not clear, but the hover text at the cursor will show `[time invalid]` in areas below the dicontinuity. We'd tried both clearing and not clearing while reworking the plotter and decided not to clear. An explicit `Clear` button would be pretty simple to add, or a marker line could be drawn at the discontinuity.

**Comment by K4KDR** [comment]
Thanks for replying!

A 'clear' button would be fantastic if you wouldn't mind putting that on your request list.  That would be even better than the old way of having to quickly change the span setting and then changing it back.

Thanks!
