### ISSUE TITLE
[FEATURE REQUEST] gr-rds

### ISSUE THREAD

**Issue by kukabu** [gqrx-sdr/gqrx#1303]
Hello

Why gqrx uses the own copy of gr-rds and not linking with gr-rds instend of?
The gr-rds project is maintained and developed.

**Comment by argilo** [comment]
At the time RDS was added (#226), gr-rds was available in many package repositories. Even today, it's not nearly as widely available as Gqrx's other dependencies (Qt, GNU Radio, gr-osmosdr). As such, making it an external dependency would force repository maintainers to add gr-rds to their repositories. So I think it probably makes sense to keep a copy of the required parts of gr-rds in Gqrx itself for now.
