### ISSUE TITLE
Why is there no Windows version?

### ISSUE THREAD

**Issue by SirTwsted** [gqrx-sdr/gqrx#1313]
Why is there no Windows version?  🤷‍♀️

**Comment by argilo** [comment]
I added a note to the README to suggest that Windows users install Gqrx through radioconda.

I consider this resolved for now, so I'll close off the issue. If someone with Windows build expertise wants to take a stab at making a stand-alone installer, that would be great. But unfortunately I don't have the skills to do it myself.
