### ISSUE TITLE
receiver.cpp:204:23: error: no matching function for call to ‘gr::top_block::disconnect

### ISSUE THREAD

**Issue by gustad** [gqrx-sdr/gqrx#1320]
I've got this error when trying to compile gqrx v2.17.3 (35030c9) with gnuradio v3.10.0.0 (9e6aeefea):

```
    /home/test/projects/sdr/gqrx.git/src/applications/gqrx/receiver.cpp: In member function ‘void receiver::set_input_device(std::string)’:
    /home/test/projects/sdr/gqrx.git/src/applications/gqrx/receiver.cpp:204:23: error: no matching function for call to ‘gr::top_block::disconnect(osmosdr::source::sptr&, int, fir_decim_cc_sptr&, int)’
      204 |         tb->disconnect(src, 0, input_decim, 0);
          |         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
```    

Is v2.17.3 not yet qualified using gnuradio 3.10 or are there any specific cmake configuration options which have to be set?

**Comment by gustad** [comment]
Thanks. I only have one gnuradio installation which I've done from source. But I've built a recent version now. So there might be traces from the old version in the install directory. I will try to clean all files left over from the old installation.

**Comment by argilo** [comment]
Were you able to resolve the problem?

**Comment by gustad** [comment]
I'm having some issues building Gnuradio-osmosdr ATM. I'll close this bug as it was probably related to the previously installed GnuRadio structure.
