### ISSUE TITLE
Regressioin in waterfall

### ISSUE THREAD

**Issue by alexbirkett** [gqrx-sdr/gqrx#1328]
Commit 9fb0eb60bb20c73f49e7bc09bbd9fd609fe51194 seems to break the waterfall for me me:

9fb0eb60bb20c73f49e7bc09bbd9fd609fe51194 looks like this:

<img width="1430" alt="Screenshot 2023-12-16 at 16 45 29" src="https://github.com/gqrx-sdr/gqrx/assets/530659/a5baf772-3685-4b2e-aa9e-8484b12b90b3">

Prior to 9fb0eb60bb20c73f49e7bc09bbd9fd609fe51194:
<img width="1434" alt="Screenshot 2023-12-16 at 16 22 29" src="https://github.com/gqrx-sdr/gqrx/assets/530659/5957e588-2e65-4881-b51d-edb6cc03e398">

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro17,1
  Model Number:	Z11D0000ZH/A
  Chip:	Apple M1
  System Version:	macOS 14.1.1 (23B81)
  Kernel Version:	Darwin 23.1.0
  Boot Volume:	Macintosh HD

**Comment by willcode** [comment]
Does the dmg in the releases area work for you?

**Comment by alexbirkett** [comment]
No the problem is reproducible with `Gqrx-2.17.3.dmg`

**Comment by argilo** [comment]
Can you show the contents of the FFT Settings pane?

**Comment by alexbirkett** [comment]
<img width="307" alt="Screenshot 2023-12-17 at 11 40 46" src="https://github.com/gqrx-sdr/gqrx/assets/530659/3cc3f5af-08ef-4a34-b3cc-dede3f2c4aa3">

Some of the other color maps appear to be working. It's just the GQRX color map that does not

**Comment by alexbirkett** [comment]
Ok this is just user error on my part. I got caught out be some changes to the settings, I assume.

<img width="1438" alt="Screenshot 2023-12-17 at 11 47 45" src="https://github.com/gqrx-sdr/gqrx/assets/530659/5355fa1e-55f7-4ac7-a243-603e9a913cab">

**Comment by argilo** [comment]
What setting fixed it? Did you have the WF dB slider set too high?
