### ISSUE TITLE
inconsistent geometry restore

### ISSUE THREAD

**Issue by kgarrels** [gqrx-sdr/gqrx#1339]
I had problems with inconsistent geometry restore.

https://github.com/gqrx-sdr/gqrx/blob/6f65661db8c6f3178da92eef400837669139e645/src/applications/gqrx/mainwindow.cpp#L532-L534

I think that

```
  // main window settings
    if (restore_mainwindow)
    {
        restoreGeometry(m_settings->value("gui/geometry",
                                          saveGeometry()).toByteArray());
        restoreState(m_settings->value("gui/state", saveState()).toByteArray());
    }
```

should be

```
    // main window settings
    if (restore_mainwindow)
    {
        restoreGeometry(m_settings->value("gui/geometry").toByteArray());
        restoreState(m_settings->value("gui/state").toByteArray());
    }
```

What do you think?

regards,
kai

**Comment by argilo** [comment]
What problems are you seeing specifically?

The fallback values do appear to be unnecessary, since the sample code in https://doc.qt.io/qt-6/restoring-geometry.html does not use them. But have you seen any behaviour change when they are removed? I think the fallback values will only be used if the settings file is missing `gui/geometry` or `gui/state`, which shouldn't normally happen.

**Comment by kgarrels** [comment]
Thanks for looking into this.

I use two displays on macOS 12.7.4, gqrx fullscreen on display 2.
Without the change, gqrx will start fullscreen on display 1.

Why do you say "fallback values"? I think, restore_mainwindow is true when a session is restored, 
https://github.com/gqrx-sdr/gqrx/blob/c830e31c325a7f1374be4b84d5cf3f4483a45c1c/src/applications/gqrx/mainwindow.cpp#L361-L363

and the the "old" code restores the "current" main window geometry (saveState()...) instead of the saved geometry.
The "current" geometry is probably what macOS remembered and restores by default.

Not sure though...what do you think?

**Comment by argilo** [comment]
> Why do you say "fallback values"?

I meant the `defaultValue` argument to `QSettings::value`, which you removed:

https://doc.qt.io/qt-6/qsettings.html#value

That argument is only used if the setting doesn't exist.

**Comment by kgarrels** [comment]
ok, I see.

Now I need to find out why it works correctly for me after my changes...
Please close the issue, let me do some debugging.

**Comment by kgarrels** [comment]
ok, found it.

The original code does not restore fullscreen at all, correct?
I had added a setting for that, and screwed it up there.

Thanks again.
