### ISSUE TITLE
Remote Control delayed responses

### ISSUE THREAD

**Issue by tarxvftech** [gqrx-sdr/gqrx#1342]
Problem and reproduction:
------------------------
When using the rigctl compatible remote control feature of gqrx 2.17.4 (NixOS) from a custom C client, responses start to be delayed by some integer number of *commands*. This delay increased with the number of commands sent.

I have reproduced the issue with netcat, looked at the traffic with tcpdump, and believe I can explain why this happens.

This is trivially reproducible by opening up `nc localhost 7356` and _copying and pasting_ the following text:
```
m
f
F 146520000
f
m
M USB
m
```
(Note that copying and pasting is critical - if you type it out, you won't see the issue. One set of input, two behaviors.)

You will notice that you only get one or maybe two response(s). Hitting enter will cause the commands that did not get a response to be processed. For the test string above, if you get two responses, you will have to send five more lines to process all the commands. Any new commands will also need five more commands to be processed, as shown here (I have manually added '>' characters to show gqrx replies for readability):
```
$ nc localhost 7356
m
f
F 146520000
f
m
M USB
m
>USB
>2700
>146520000

>RPRT 0

>146520000

>USB
>2700

>RPRT 0

>USB
>2700

m





>USB
>2700
```

The number of commands that are incorrectly 'buffered' will increase every time you send multiple commands in a short window. Note that this is not related to Nagle's, or whether commands arrive in single or multiple TCP packets, and indeed neither of those could cause this behavior. 

I don't know a thing about socket programming as it relates to QT specifically, but I believe it's related to a mismatch between the Signal API and GQRX's usage of it for line-oriented commands.

Here's what is happening:
**`RemoteControl::startRead()` is called each time readyRead fires.**

**It then reads _one line_ off the buffer.**

So what happens when readyRead is fired once, and the resulting read (if not line-oriented) *would have* contained multiple commands? 

This is my informed guess as to what's happening. Since we are only reading one line off the buffer, not all commands that have arrived with this readyRead signal are processed, only the first one. This means if we send 6 commands, one will be processed. When we get another line later, readyRead is fired again ... and we get the next of the lines that were remaining from the first batch. At no point do we process all incoming bytes, we are making the assumption that one readyRead means one command, and that doesn't necessarily follow.

I note that the [readyRead documentation](https://doc.qt.io/qt-6/qiodevice.html#readyRead) says:
> (do not emit it [readyRead] only because there's data still to be read in your buffers)

So we know that we shouldn't expect another signal to process more bytes if our handling of the first signal didn't consume them.

The fix might make good use of [`canReadLine()`](https://doc.qt.io/qt-6/qiodevice.html#canReadLine) together with readLine, or use [`bytesAvailable()`](https://doc.qt.io/qt-6/qiodevice.html#bytesAvailable) as a hint.

From looking at the user group, I found a couple more people who seem to have encountered this. They were not able to articulate it well at the time, but the symptoms they describe match mine.

I've struggled with getting the dependencies all together, sorry for not including a patch with the bug report!

**Comment by argilo** [comment]
Thanks for the report and the detailed investigation. I'll have a look at this soon and try to make a patch.
