### ISSUE TITLE
libgnuradio-osmosdr.so error during building of gqrx

### ISSUE THREAD

**Issue by nerdlikeme** [gqrx-sdr/gqrx#1350]
[ 98%] Linking CXX executable gqrx
/usr/bin/ld: /usr/local/lib/libgnuradio-osmosdr.so: undefined reference to `boost::this_thread::hiden::sleep_for(timespec const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/gqrx.dir/build.make:1230: src/gqrx] Error 1
make[1]: *** [CMakeFiles/Makefile2:235: src/CMakeFiles/gqrx.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by argilo** [comment]
I suspect this is a problem with your setup, and not with Gqrx itself.

For help building Gqrx from source, I would suggest using the user support group: https://groups.google.com/g/gqrx
