### ISSUE TITLE
logger_set_level: Bad level type.

### ISSUE THREAD

**Issue by Udivyasree** [gqrx-sdr/gqrx#1352]
$ gnss-sdr --config_file=/home/divyasree/gnss-sdr/my-first-GNSS-SDR-receiver.conf
Initializing GNSS-SDR v0.0.11 ... Please wait.
Logging will be written at "/tmp"
Use gnss-sdr --log_dir=/path/to/log to change that.
logger_set_level: Bad level type.

GNSS-SDR program ended.

**Comment by argilo** [comment]
I imagine you're looking for GNSS-SDR (https://github.com/gnss-sdr/gnss-sdr), which has no connection to Gqrx SDR.
