### ISSUE TITLE
macOS ARM Compatibility?

### ISSUE THREAD

**Issue by EVRiNOM** [gqrx-sdr/gqrx#1353]
Hi!
I apologize in advance if it's a dumb question or something, but can someone please make a native build for ARM processors on macOS?
I know I can use Rosetta but I don't want to install it, like to keep it "clean".
Thank you.

**Comment by Axpelle** [comment]
The latest version runs very smoothly on M1/M2 chips. You won't even know Rosetta is activated.

**Comment by EVRiNOM** [comment]
> The latest version runs very smoothly on M1/M2 chips. You won't even know Rosetta is activated.

I'm sure it does, it's not that. Consider me weird.

**Comment by argilo** [comment]
There is already an issue open for this. Please see #1104.

**Comment by EVRiNOM** [comment]
> There is already an issue open for this. Please see #1104.

My bad, thank you.
