### ISSUE TITLE
can't open TCP connection

### ISSUE THREAD

**Issue by terminaldweller** [gqrx-sdr/gqrx#1358]
when i run gqrx i get the following gui popup:

```txt
can't open TCP connection

Please select another device.
```
my device string config line:
```
rtl_tcp=127.0.0.1:1234
```
```sh
$ uname -a
Linux voidbox 6.6.30_1 #1 SMP PREEMPT_DYNAMIC Sat May  4 01:16:03 UTC 2024 x86_64 GNU/Linux
```

```sh
$ rtl_test -t
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6
[R82XX] PLL not locked!
Sampling at 2048000 S/s.
No E4000 tuner found, aborting.
```
gqrx version: `2.17.5`
gnu radio version: `3.10.8.0`

How can I go about troubleshooting this?

**Comment by argilo** [comment]
Unless you're trying to access a remote RTL-SDR on another machine, you should select the local RTL-SDR device (device string `rtl=0`).

For further help, I would suggest asking in the Google group (https://groups.google.com/g/gqrx) rather than opening a GitHub issue.
