### ISSUE TITLE
How to compile and generate the exe running on the Windows system

### ISSUE THREAD

**Issue by Yiyunfei24** [gqrx-sdr/gqrx#1363]
Hello. I'm new to SDR and programming, and I want to redevelop GQRX and use it with USRP, but the platform is windows. Now that I can use Qt to compile the source code on ubuntu, how should I compile and generate the exe running on the Windows system?

**Comment by argilo** [comment]
Hi @Yiyunfei24. This issue tracker is used to file bug reports and feature requests. For questions about building or using Gqrx, please use our Google group: https://groups.google.com/g/gqrx
