### ISSUE TITLE
+++ killed by SIGSEGV +++ and sdrplay

### ISSUE THREAD

**Issue by kelogs** [gqrx-sdr/gqrx#1364]
On a raspberry pi 3b+ (not much sense attempting `gdb` I think), with gqrx built from `master` branch

Before I fill in all the details, I have managed to capture an `strace` log - attached.

Does anything give, should I continue with my setup and observations ? 

Thank you
[strace_gqrx.log](https://github.com/user-attachments/files/16338870/strace_gqrx.log)

**Comment by argilo** [comment]
Hi @kelogs,

For help building Gqrx from source, please use the Google Group: https://groups.google.com/g/gqrx
