### ISSUE TITLE
Compiled gqrx on mint 22 will not run

### ISSUE THREAD

**Issue by Peter-PA0PJE** [gqrx-sdr/gqrx#1365]
I updated my PC to linux Mint 22 (Mate desktop) and ran gqrx from the prompt after noticing that it would not launch, so I decided to compile it again
When launched from a terminal I get:
gqrx: error while loading shared libraries: libgnuradio-digital.so.3.10.1: cannot open shared object file: No such file or directory

So I deleted anything regarding gqrx and compiled it again, same error.

Well this is correct, the existing file is libgnuradio-digital3.10.9t64 and all other installed libgnuradio libraries have this

The install did not give any errors while compiling about missing or incorrect libs.

The appimage, however runs OK. Is that because in the appimage previous libraries have been used?
Is it possible for me to correct this myself by editing files?

Thanks in advance to look into this.
73, Peter PA0PJE

**Comment by argilo** [comment]
For help building Gqrx from source, please use the support group: https://groups.google.com/g/gqrx

Alternatively, you could use the `gqrx-sdr` package which should be available in Mint's package repository.
