### ISSUE TITLE
stuttered/jerky sound + reception going bad

### ISSUE THREAD

**Issue by kelogs** [gqrx-sdr/gqrx#1366]
Hi,

```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.4.42-v8+ #1319 SMP PREEMPT Wed May 20 14:18:56 BST 2020 aarch64 GNU/Linux
pi@raspberrypi:~ $ sudo apt install gr-osmosdr
gr-osmosdr is already the newest version (0.1.4-14+b10).
pi@raspberrypi:~ $ sudo apt install gqrx-sdr
gqrx-sdr is already the newest version (2.11.5-1+b2).

```

> SoapySDR release v0.6.1
> https://github.com/pothosware/SoapySDRPlay2 - master branch
> driver: SDRplay_RSP_API-ARM64-2.13.1.run
> 

![Screenshot_20240728_191916](https://github.com/user-attachments/assets/9cebc4f7-d90a-4f51-97a3-29e8a6ca1391)
![Screenshot_20240728_192944](https://github.com/user-attachments/assets/71cfda28-4373-47f1-a7ae-79c15ab7a8e4)
![Screenshot_20240728_193017](https://github.com/user-attachments/assets/2d6cdb48-a091-405a-bc14-e9e7faf42c14)

I have tried many other software combos - all fine on my old linux PC, never fine on my Rpi 3b; usually on Rpi there is the sound stutter + OS crash problem. With the combo describe there is only sound stutter + vertical stripes on waterfall issue.

Anything gives ? 
Thanks!

**Comment by argilo** [comment]
For help with troubleshooting, please use the Google group: https://groups.google.com/g/gqrx
