### ISSUE TITLE
Filter width is 'too wide' 

### ISSUE THREAD

**Issue by T-McBride** [gqrx-sdr/gqrx#1368]
Filter width appears too wide regardless of selection. Screenshots attached. Everything else works but audio is obviously static. 

Experienced with 2.17.5 app image and with 2.17.2 distro package, Gentoo linux, 6.6.38 kernel. SDR is hackrf with sample rate of 8M.

![Screenshot_20240807_200733-1](https://github.com/user-attachments/assets/e319c8d0-7fb9-4e9f-9559-da637b935fc6)

![Screenshot_20240805_160938](https://github.com/user-attachments/assets/5d32d0f7-ad01-448c-bf83-beec8b9d2836)

Thanks in advance.

**Comment by argilo** [comment]
The filter widths look correct to me.

Keep in mind that the frequency listed at the top is in Hz. You're tuned very low. HackRF can't receive much below 1 MHz.

**Comment by T-McBride** [comment]
Perhaps I'm missing something as WFM "consumes" the entire fm bandwidth and then some.
e.g. set to 91 fm but filter occupies ~32 to ~150 FM. 

![Screenshot_20240807_203637](https://github.com/user-attachments/assets/faab2375-8d14-402e-82a9-f294fbe7098a)


If this is correct apologies for misunderstanding and please close. Just confused as can't get any FM reception in GQRX but have no issues in GNU radio. (?) 

TY

**Comment by T-McBride** [comment]
Just re-read your point and realized my decimal error. My sincere apologies. Set to 91.000.00 etc no issues. Appreciate the quick reply and great software.

**Comment by argilo** [comment]
I'm glad to hear you sorted it out.
