### ISSUE TITLE
AGC: Hardware vs Software

### ISSUE THREAD

**Issue by kelogs** [gqrx-sdr/gqrx#1371]
> I think you are confusing hardware AGC with software AGC. The Airspy HF+ has no programming interface for setting any gain.
> 
> The AGC control you are referring to in SDR# must be the software AGC. Gqrx has that too under "Receiver Options". The hardware AGC is only available for some devices like RTLSDR. Unfortunately, gqrx can not know whether a device supports hardware AGC or not, so the only options I have is to show it or not for all devices.

I would like to hear a few words on these two AGCs.

AFAICT GQRX software implementation in CAgc class is not correlated in any way with Gnuradio's hardware AGC (in osmosdr::source class). Is it fine to use them both simultaneously ? Any other tips welcome.

Thank you

**Comment by argilo** [comment]
This issue tracker is for bug reports and feature requests. For questions about Gqrx functionality, please use the discussion group: https://groups.google.com/g/gqrx
