### ISSUE TITLE
GQRX cant detect hackrf

### ISSUE THREAD

**Issue by Lolington98** [gqrx-sdr/gqrx#1372]
GQRX cant detect HackRF One. im getting the message: Failed to open device. cant open file. please select another device. 
I then press ok and i get the configure I/O window. any tips?

**Comment by Sasszem** [comment]
Is your hackrf recognized by your system? What is the output of `hackrf_info`?

**Comment by argilo** [comment]
This issue tracker is only for bug reports & feature requests. To ask questions about using Gqrx, please use the Google group: https://groups.google.com/g/gqrx
