### ISSUE TITLE
Missing IF/BB gain settings for RTL_SDR v3 (RTL2838) using Gqrx-2.17-x86_64.AppImage

### ISSUE THREAD

**Issue by jonnycat5000** [gqrx-sdr/gqrx#1376]
Missing IF/BB gain settings for RTL_SDR v3 (RTL2838) using Gqrx-2.17-x86_64.AppImage under Ubuntu 22.04.  The only gain setting available is the slider for LNA (see image [here](https://imgur.com/a/yXtbMYT))

**Comment by argilo** [comment]
This is the expected behaviour. The RTL-SDR driver only uses a single gain stage (LNA), except for e4000-based devices which have two stages (LNA & IF).
