### ISSUE TITLE
Your files receiver.cpp.o was error do you fix it yet?

### ISSUE THREAD

**Issue by Winjangza** [gqrx-sdr/gqrx#1387]
/home/xavier/gqrx.git/src/applications/gqrx/receiver.cpp:204:46: error: no matching function for call to ‘gr::top_block::disconnect(osmosdr::source::sptr&, int, fir_decim_cc_sptr&, int)’
  204 |         tb->disconnect(src, 0, input_decim, 0);
I can't 'make' to install it because of this sir.But I can 'cmake'

**Comment by argilo** [comment]
Please see these previous issues: #1320, #1268, #1187.

The problem is likely that you have multiple versions of GNU Radio installed on your system.
