### ISSUE TITLE
Error 'make' in gqrx-git 

### ISSUE THREAD

**Issue by Winjangza** [gqrx-sdr/gqrx#1389]
Here is my error, how to solve this sir?
xavier@ubuntu:~/gqrx.git/build$ make
[  1%] Automatic MOC for target gqrx
[  1%] Built target gqrx_autogen
make[2]: *** No rule to make target '/usr/lib/aarch64-linux-gnu/libgnuradio-osmosdr.so', needed by 'src/gqrx'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:248: src/CMakeFiles/gqrx.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by argilo** [comment]
For help building Gqrx, please use the discussion group, not the issue tracker:

https://groups.google.com/g/gqrx

Thanks.
