### ISSUE TITLE
GQRX Crash: rtlsdr_read_async returned with -5

### ISSUE THREAD

**Issue by robotastic** [gqrx-sdr/gqrx#162]
I am having an error with GQRX crashing about 2 seconds after I hit the button to go live. It is a pretty clean system running GR3.7. It looks like a couple of other people are having this problem: http://lists.gnu.org/archive/html/discuss-gnuradio/2014-03/msg00468.html

I have tried both the Master versions of GQRX and GR-OsmoSDR and the release versions and that hasn't helped. Running as SUDO doesn't seem to help. Anything else I should try?

linux; GNU C++ version 4.7.3; Boost_104900; UHD_003.007.000-1-ga8caec5f

gr-osmosdr v0.1.0-78-g1e8b45d0 (0.1.1git) gnuradio 3.7.3
built-in source types: file fcd rtl rtl_tcp uhd rfspace 
Using Volk machine: ssse3_64_orc
gr-osmosdr v0.1.0-78-g1e8b45d0 (0.1.1git) gnuradio 3.7.3
built-in source types: file fcd rtl rtl_tcp uhd rfspace 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Rafael Micro R820T tuner
Exact sample rate is: 1500000.014901 Hz
rtlsdr_read_async returned with -5
gqrx: pthread_mutex_lock.c:65: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
Aborted (core dumped)

**Comment by rfrail3** [comment]
I have the same error "rtlsdr_read_async returned with -5" on a Debian Wheezy and the problem was with libusb. Using the last version from backports libusb-1.0-0:amd64 2:1.0.19-1~bpo70+1 solved it.

Thanks for the info guys!
