### ISSUE TITLE
Trying to compile under gentoo

### ISSUE THREAD

**Issue by s-hell** [gqrx-sdr/gqrx#174]
I'm trying to compile gqrx under linux. I've compiled gnuradio from sources.
Running qmake gives the following error message:

`[user@host:~/git/gqrx/build] (master)$ qmake ..
Project MESSAGE: Gqrx configured with pulseaudio backend
Project MESSAGE: No prefix given. Using /usr/local
Project ERROR: Package gnuradio-analog not found`

But gnuradio-analog is installed:

`[user@host:~/git/gqrx/build] (master)$ locate gnuradio-analog
...
/usr/local/lib64/libgnuradio-analog-3.7.4git.so
/usr/local/lib64/libgnuradio-analog-3.7.4git.so.0
/usr/local/lib64/libgnuradio-analog-3.7.4git.so.0.0.0
/usr/local/lib64/libgnuradio-analog.so
/usr/local/lib64/pkgconfig/gnuradio-analog.pc`

Any idea?

**Comment by filipdns** [comment]
Hello s-hell did you solve this issue? I got same and add path doesn't help...
thank you
