### ISSUE TITLE
Zoom not working in OS X

### ISSUE THREAD

**Issue by CallumA** [gqrx-sdr/gqrx#197]
Under OS X the zoom function does not work, instead scrolling within the frequency axis just causes the frequency to change (presumably because this was the last function used).

I have tried everything from scrolling up/down and left/right on the trackpad and an external USB mouse with the same effect. I've looked through all the settings so I'm /pretty/ sure this one's an actual issue.

**Comment by natevw** [comment]
Thanks, this was helpful. The zoom slider (in FFT settings) disappeared after the last rebuild on my Mac and I was not aware I could zoom via the scroll wheel as above. More convenient than the old way!

**Comment by csete** [comment]
@natevw The zoom slider should still be there. Btw. zooming and panning using the mouse on the axes has always been there. It is the zoom slider that is new.

**Comment by natevw** [comment]
Here is what the FFT settings looks for me now:

<img width="280" alt="screen shot 2015-10-24 at 1 09 00 am" src="https://cloud.githubusercontent.com/assets/265902/10709649/e6dc4488-79eb-11e5-8bd6-80e76ef3d3ea.png">

(Also the FM RDS tab has gone away too…) About dialog says Gqrx 2.3.2, I installed via homebrew (https://github.com/chleggett/homebrew-gqrx/blob/master/gqrx.rb).

**Comment by csete** [comment]
Both the zoom slider and RDS info have been added after the 2.3.2 release, see https://github.com/csete/gqrx/blob/master/news.txt
