### ISSUE TITLE
Edited bookmark name is not applied immediately to spectrum display

### ISSUE THREAD

**Issue by darrenfreeman** [gqrx-sdr/gqrx#263]
Using the latest source from git, under Linux/KDE.

Tune in to a bookmark.

Edit the name of the bookmark.

The spectrum display shows the old bookmark name until the frequency is changed. Then it updates to the new name.

**Comment by csete** [comment]
This is also the case if a bookmark is deleted.

**Comment by darrenfreeman** [comment]
Yes, I discovered that later too :)

**Comment by kolbma** [comment]
Would be fixed in https://github.com/kolbma/gqrx/tree/bookmarks-ext
