### ISSUE TITLE
File playback device arg does not apply frequency 

### ISSUE THREAD

**Issue by devnulling** [gqrx-sdr/gqrx#962]
Using the `freq=` param of the device string arg, GQRX does not properly set the frequency.

For example this device arg:

    file=/data/test.fc32,freq=900e6,rate=40e6,repeat=true,throttle=true

When GQRX is started, it defaults to `14.236.000`

Tested on master 272bd75e8cb33ff54d2d8f71295295dcdbf4b962

**Comment by argilo** [comment]
I expect this happens because Gqrx doesn't ask gr-osmosdr what the current center frequency is. #951 has a similar root cause.
