### ISSUE TITLE
Gain level setting not applied by default on SDRplay RSPdx

### ISSUE THREAD

**Issue by AsciiWolf** [gqrx-sdr/gqrx#979]
Gqrx 2.14.4 on Fedora 34 with SDRplay RSPdx (using SoapySDR 0.7.2 with SDRplay RSP API 3.07.1). Gain (IFGR and RFGR) level seems to be set to a minimal gain when Gqrx is started. The sliders are displayed with correct values in Gqrx, but I have to manually check and uncheck the "Hardware AGC" checkbox to make the values be actually applied.

**Comment by argilo** [comment]
I think the most likely explanation is a bug in gr-osmosdr. Unfortunately I don't have SDRplay hardware to test with, so there's not much I can do for now.

**Comment by dl2kcd** [comment]
I encounter the same with an SDRplay RSP2pro using gr-osmosdr from willcode. I analyzed the problem with gdb and found the following problem.

In gr-osmosdr/lib/source_impl.cc, function `bool source_impl::set_gain_mode( bool automatic, size_t chan )` does this:
```
        if ( _gain_mode[ chan ] != automatic ) {
          _gain_mode[ chan ] = automatic;
          ...
        }
```
This is apparently the only place where `_gain_mode` is written. It is initially an empty vector, and on the first call, the condition check accesses a vector element before it is initialized. That returns `0`, meaning no automatic gain. So if the "Hardware AGC" box is not checked on start, the function is called with `automatic == 0`, and then wrongly assumes that this has been already set. Unfortunately, the default inside the SDRplay specific routines is to have AGC enabled, causing an inconsistency. The manual gain settings are therefore overridden by the AGC.

By checking the AGC box before starting, the function gets called with a nonzero value in `automatic`, so `_gain_mode[ chan ]` gets properly initialized and the change is propagated to the SDRplay driver. Unchecking AGC again then works as expected.

That particular piece of code still exists in the upstream code of gr-osmosdr from osmocom, apparently also without proper initialization.

In theory, GQRX could work around this by emulating the check/uncheck of the AGC box in software, but it would be better if gr-osmosdr was fixed to correctly initialize `_gain_mode` or check if `_gain_mode[ chan ]` exists before reading it.

**Comment by dl2kcd** [comment]
This change in gr-osmosdr/lib/source_impl.cc fixes it for me:
```
-        if ( _gain_mode[ chan ] != automatic ) {
+        if ( (_gain_mode.count(chan) == 0) || (_gain_mode[ chan ] != automatic) ) {
```

**Comment by AsciiWolf** [comment]
Cool, thanks! Any chance this fix could be submitted to upstream?

**Comment by AsciiWolf** [comment]
Upstream ticket: https://osmocom.org/issues/5562

**Comment by AsciiWolf** [comment]
The issue was [patched downstream](https://src.fedoraproject.org/rpms/gr-osmosdr/c/01cd07aef4d2c20e3209cec1eb920837068fdfb1?branch=rawhide) in Fedora. Let's hope it will also be fixed in upstream and/or in other Linux distributions.

**Comment by argilo** [comment]
Perhaps the issue would get more visibility in Osmocom's gitea instance: https://gitea.osmocom.org/sdr/gr-osmosdr/issues

**Comment by AsciiWolf** [comment]
Thanks!
