### ISSUE TITLE
S-meter oscillation

### ISSUE THREAD

**Issue by LongnoseRob** [gqrx-sdr/gqrx#994]
As mentioned in the matrix channel, I observe regularrly, that after 10h or more of continious operation the S-meter indication seems to start pulsing/oscilalting.
Switching the decoder to another mode and back solves this issue (NFM->AM-->NFM).
Audio-decoding does not seem to be affected.
Running gqrx 2.14.5 built from sources.

Will try to get some video or still-pictures of this happening in the next days.

**Comment by LongnoseRob** [comment]
The problem also occurs when running a file-source and using big FFT numbers and high refresh-rates.

**Comment by argilo** [comment]
Closing, since #1006 should fix this.
