### ISSUE TITLE
feature request: left-right arrow keys change digit

### ISSUE THREAD

**Issue by pidloop** [gqrx-sdr/gqrx#995]
Hi, loving 2.14.5 on macOS 11.6 with CloudIQ, many thanks.

I can click on a frequency digit and increase or decrease with the up-down arrow keys. Would be great if I could move to an adjacent digit with the left-rights keys.

Thanks and 73, Elwood, WB0OEW

**Comment by LouDou** [comment]
This is a little strange, it seems to work under Linux. The frequency control widget uses the standard `Qt::Key_Left`/`Qt::Key_Right` codes in the keypress handler, which should work if `Qt::Key_Up`/`Qt::Key_Down` are already working.

**Comment by pidloop** [comment]
Yes, strange, I would have expected the implementation to be something like that.

Here are some more clues: if I take care to use just up and down and change digits with the mouse then all ok. But as soon as I hit left or right, then up and down stop working too. If use the mouse the select a different digit then use up or down the app soon crashes with the message **get_center_freq failed**.

**Comment by LouDou** [comment]
Part 1: Left/Right moves the mouse cursor. On macOS (tested on Monterey) this is only allowed if you enable in settings > Security & Privacy > Privacy > Accessibility > Allow the apps below to control your computer > check Gqrx?

Part 2: even when the cursor is moved, the digit focus hasn't changed, therefore the next up/down doesn't work. I'll look into this a little bit

**Comment by LouDou** [comment]
Part 3: I'm not sure the app really needs to even move the mouse cursor at all. The widget has enough code in it to allow changing the active digit without doing this. What's the use of moving the cursor? Especially as it actually will obscure the active digit as wel?

**Comment by pidloop** [comment]
Still running Big Sur here. Gqrx.app was already checked.

If I said cursor I misspoke, I'm only interested in moving the digit focus with the l/r arrow keys. Thanks.

**Comment by markjfine** [comment]
Don't mean to parachute in on someone else's feature request, but wouldn't it be more feasible to use the left/right arrow keys as a means for up/down tuning of a user-selected (or band-standard) stepsize, like on other tuning packages? That seems more of a logical, consistent, and user-friendly way to easily slew through a set of frequencies.

**Comment by LouDou** [comment]
> If I said cursor I misspoke, I'm only interested in moving the digit focus with the l/r arrow keys. 

Yes, I understand - the way the widget implements this right now is to actually move the mouse cursor over the digit and use the mouse move to set the digit focus - which is somewhat baffling. I have a solution that avoids this, and sets the focus directly without moving the mouse. I was curious though why it was implemented this way, if there's a good reason to use this method or not?

**Comment by pidloop** [comment]
No clue, moving the cursor programmatically is generally a bad UX idea in any case.

**Comment by argilo** [comment]
@pidloop I've merged #999, which should fix this issue. (Thanks, @LouDou!) A pre-release build is available here, in case you'd like to test it out prior to the next release: https://github.com/gqrx-sdr/gqrx/actions/runs/1594587637

**Comment by pidloop** [comment]
Perfect! Many thanks to all involved.

**Comment by argilo** [comment]
This fix is now in the 2.15.1 release: https://github.com/gqrx-sdr/gqrx/releases/tag/v2.15.1
